---

- name: Delete default nginx site
  action: file path=/etc/nginx/sites-enabled/default state=absent
#  notify: nginx restart

- name: Copy nginx config
  copy: src=files/nginx/nginx.conf dest=/etc/nginx/nginx.conf
#  notify: nginx restart

- name: Ensure that nginx is started
  service: name=nginx state=started enabled=yes
