---

- name: Create users
  user: name={{ item }} state=present generate_ssh_key=yes home=/home/{{ item }}
  with_items:
    - yyyyy_ooo

- name: Clone homepage repo
  git: repo=git@github.com:v0y/homepage.git dest=/home/yyyyy_ooo/repos/homepage accept_hostkey=yes force=yes

- name: Copy homepage uwsgi config
  copy: src=files/yyyyy_ooo.ini dest=/etc/uwsgi/apps-available/yyyyy_ooo.ini owner=yyyyy_ooo

- name: Install homepage python dependencies
  pip: chdir=/home/yyyyy_ooo/repos/homepage executable=/home/yyyyy_ooo/venvs/yyyyy_ooo/bin/pip requirements=/home/yyyyy_ooo/repos/homepage/requirements.txt

- name: Change homepage venvs owner
  file: path=/home/yyyyy_ooo/venvs owner=yyyyy_ooo state=directory recurse=yes

- name: Restart uwsgi
  command: supervisorctl restart yyyyy_ooo_uwsgi

- name: Delete default nginx site
  action: file path=/etc/nginx/sites-enabled/default state=absent
#  notify: nginx restart

- name: Copy nginx config
  copy: src=files/nginx/nginx.conf dest=/etc/nginx/nginx.conf
#  notify: nginx restart

- name: Copy homepage nginx config
  copy: src=files/nginx/yyyyy_ooo dest=/etc/nginx/sites-enabled/yyyyy_ooo

- name: Ensure that nginx is started
  service: name=nginx state=started enabled=yes
