---

- name: Install things with apt-get
  apt: force=yes name={{ item }} state=present
  with_items:
    - git
    - build-essential
    - nginx
    - python-pip
    - python-dev
    - python3-dev
    - python-virtualenv
    - uwsgi
    - uwsgi-core
    - uwsgi-plugin-python
    - uwsgi-plugin-python3
    - libxslt-dev
    - libxml2-dev
    - libffi-dev
